
CreateThread(function()
    ReplaceHudColourWithRgba(116, _CONFIG.RGBA.LINE.RED, _CONFIG.RGBA.LINE.GREEN, _CONFIG.RGBA.LINE.BLUE, _CONFIG.RGBA.LINE.ALPHA)
    ReplaceHudColourWithRgba(117, _CONFIG.RGBA.STYLE.RED, _CONFIG.RGBA.STYLE.GREEN, _CONFIG.RGBA.STYLE.BLUE, _CONFIG.RGBA.STYLE.ALPHA)
    ReplaceHudColourWithRgba(142, _CONFIG.RGBA.WAYPOINT.RED, _CONFIG.RGBA.WAYPOINT.GREEN, _CONFIG.RGBA.WAYPOINT.BLUE, _CONFIG.RGBA.WAYPOINT.ALPHA)

end)